# 服务器
server:
  port: 8888
spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/single_architecture?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 连接池
    druid:
      # 最小空闲
      min-idle: 5
      # 最大存活连接
      max-active: 20
      # 初始化连接数
      initial-size: 5
      # 配置监控服务器
      stat-view-servlet:
        #是否允许开启监控
        enabled: true
        #是否允许重置监控数据
        reset-enable: true
        #druid访问路径
        url-pattern: /druid/*
      # 监控统计过滤器
      filters: stat,wall,log4j2
      # 检查关闭空闲连接的时间周期
      time-between-eviction-runs-millis: 6000
      # mergeSql，慢SQL记录
      connect-properties: druid.state.mergeSql=true
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
# Mybatis Plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
# Token超时时间（单位秒）
#token:
  # 8个小时28800
  #accessTokenExpire: 28800
  # 15天1296000
  #refreshTokenExpire: 1296000
# URI映射路径
route-map:
  uri: /upload/
  path: /Volumes/Project/upload/
# 代码生成器生成路径
# generate-path: /Users/machine/Desktop/生成/